# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetname',
            name='asset_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
