# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetname', '0002_auto_20181018_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetname',
            old_name='asset_name',
            new_name='asset_type',
        ),
    ]
