# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmanager',
            name='asset_serial_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
