# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0002_assetmanager_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmanager',
            name='asset_serial_number',
            field=models.IntegerField(unique=True),
        ),
    ]
